The price is changing
qbcore-framework/LegacyFuel pull request #9
Opened 2021-10-12 08:25 UTC by darknight2590

Adding a new economic variable cost
The price is changing

2021-10-12 08:26 UTC, darknight2590 commented
A new idea for more realism
Add a variable price per liter of gasoline
To add more realism

2021-10-14 16:24 UTC, TechnoBehemoth commented on source/fuel_client.lua
> +local todaycoast = 0
```suggestion
local todaycost = 0
```
Typo fix for clarity

2021-10-14 16:24 UTC, TechnoBehemoth commented on source/fuel_client.lua
> +			todaycoast = extraCost
```suggestion
			todaycost = extraCost
```

2021-10-14 16:24 UTC, TechnoBehemoth commented on source/fuel_client.lua
> +			local extraString = "\n" .. Config.Strings.TotalCost .. ": ~g~$" .. Round(todaycoast, 1)
```suggestion
			local extraString = "\n" .. Config.Strings.TotalCost .. ": ~g~$" .. Round(todaycost, 1)
```

2021-10-17 19:02 UTC, Eralpozcan requested changes
Please make the changes.

2021-11-21 02:21 UTC, merged